
project_id = "mpzqlidtvlbijloeusuj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
enable_confirmations = false

[functions.payfast-subscribe]
verify_jwt = true

[functions.payfast-notify]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = true

[functions.simulate-trial-end]
verify_jwt = true

[functions.mark-time-slot]
verify_jwt = false
